{% set name = "PyTrilinos" %}
{% set version = "12.16.1git" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/trilinos/Trilinos.git
  git_branch: trilinos-release-12-16-branch
  patches:
    - 0001-Fixed-SWIGEMPTYHACK-and-missing-namespace-imports.patch

build:
  number: 5
  skip: true  # [win]

requirements:
  build:
    - cmake >=2.8.11
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - {{ mpi }}
    - mpi4py
    - python
    - swig >=3.0.11
    - numpy >=1.12
    - libblas
    - liblapack
    - boost >=1.65.0
  run:
    - {{ mpi }}
    - mpi4py
    - python
    - {{ pin_compatible('numpy') }}
    - boost >=1.65.0

test:
  requires:
    - cmake >=3.9.6
    - mpi4py
  imports:
    # - PyTrilinos.Tpetra
    # - PyTrilinos.Domi
    - PyTrilinos.Teuchos
    - PyTrilinos.Epetra
    - PyTrilinos.TriUtils
    - PyTrilinos.EpetraExt
    - PyTrilinos.AztecOO
    - PyTrilinos.Galeri
    - PyTrilinos.Amesos
    - PyTrilinos.IFPACK
    - PyTrilinos.Komplex
    - PyTrilinos.ML
    - PyTrilinos.Anasazi

about:
  home: https://trilinos.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary:
    Python interfaces to Sandia's suite of HPC solvers and enabling technologies
  description:
    Python interfaces to fast, compiled object-oriented algorithms and
    enabling technologies for the solution of large-scale, complex
    multi-physics engineering and scientific problems.

    (This package is a work-in-progress. Many modules, including Tpetra,
    are missing.)
  dev_url: https://github.com/trilinos/Trilinos

extra:
  recipe-maintainers:
    - wfspotz
